### ISSUE TITLE
팀 소개 작성

### ISSUE THREAD

**Issue by Ricepunchb** [sjki928/Earlyadottor#1]
# 일정
~ 24.12.02. 2359

# 포스트 초안
안녕하세요! 현재 종각역에서 인턴을 하고 있는 저희는 "종각역 프롤레타리아"입니다. 

과 동기로서 만난 저희는 같은 연구실, 같은 동네에서 인턴을 하며 6년째 인연을 이어오고 있습니다.

저희는 수학과 데이터 사이언스, AI를 연구하는 사람으로서 이런 최첨단 기술이 디지털 네이티브 세대만의 전유물이 아닌,

당장 키오스크도 쓰기 어려워 하시는 어르신들께도 널리 쉽고 유용하게 쓰였으면 하는 마음으로 이번 공모전에 지원하게 되었습니다.

잘 부탁 드리겠습니다!!

**Comment by Ricepunchb** [comment]
# 팀 소개용 PPT 만들기
[템플릿 링크](https://docs.google.com/presentation/d/1TY6Y5QS9esXGXQCm7_sBTxGv8U2b8c_z/edit?usp=sharing&ouid=101042302487174174133&rtpof=true&sd=true)

**Comment by sjki928** [comment]
혹시 미리 캔버스의 권한 부여가 가능하신지에 대한 윤허에 대한 여부를 여쭤봐도 될까요?
bosung928@gmail.com 입니다.

**Comment by Ricepunchb** [comment]
https://www.miricanvas.com/v/13zaltf?mode=templateshare
비번 : whdrkrdur

**Comment by Ricepunchb** [comment]
https://www.earlyadottor.com/c/9a93bd/719eaa
