### ISSUE TITLE
Project One: Recommendation of Hospital

### ISSUE THREAD

**Issue by sjki928** [sjki928/Earlyadottor#2]
전지역에서 가까운 지점을 찾기 어려우니 지하철 역이라는 특수성을 가지고 접근하면 좋을듯

지역구로 하면 동면읍까지 신경 써야할 수 도 있어서 전국 지하철역으로 줄여도 크긴 할듯.. 서울을 제일 마지막으로 하는것도 고려

지하철역의 주소를 입력하고 분과를 입력할 때 잘 뱉는 prompt

'잘 뱉는'의 기준: 지도상 가장 인근 병원부터 5개의 병원을 알려달라해서 몇개나 맞췄는지

가능 Method:
1. Warmstart : 아무런 기본 정보가 없을 때 https://github.com/AIML-K/epoxy-alpha/issues/221 해당 이슈에서 댓글 단 것 처럼 task Draft작성에 도움을 줌
2. finetune : https://arxiv.org/abs/2411.10541?utm_source=pytorchkr&ref=pytorchkr 해당 논문 처럼 입력으로 받을 정보의 format 확인
(생각보다 일이 커질 수 있어서 너무 많은 종류를 실험하긴 무리일 수 있음)

**Comment by Ricepunchb** [comment]
# 공지 전문
[프롬프트 템플릿 1차 기획안 제출]

✔️ 기한: 12/03(화) 00:00 ~ 12/09(월) 23:59
     *제출기한 이후 수정 시 패널티 있음(관리자 계정에서 수정 시간 확인 가능)

✔️ 필수 포함 내용: 
     - 표지 제외 10Page 이상 PDF로 첨부하여 Post 등록
     - 1차 기획안 내용 간략하게 요약하여 Post 본문에 기재
     - 기획 의도, 제작 아이디어, 검증 계획 등이 필수로 포함 되어야 함

🎁 우수상 : 5만원 상당 기프티콘 (10팀)
     (** 조건에 부합하지 않는 제출물에 대해서는 운영진이 보완을 요청할 수 있습니다.)

✍️ 참고 사항:

- PDF 제출시, 한글, 워드, PPT 등 형식은 관계 없습니다만, 추후 우수 팀으로 선정되어 프레젠테이션을 진행할 것을 감안하면, 가급적 가로 PPT로 제작 후 PDF로 제작하는 것을 권장 드립니다.

- 1차 기획안 평가 기준은 ‘성실성’과 ‘완성도’ 입니다. 추후 최종 기획안 제출을 위한 준비 과정이라고 보시면 되며, 1차 기획안 평가 결과가 최종 기획안에 영향을 주진 않습니다.

- 아시다시피 에이닷 프롬프트 템플릿은 [에이닷 웹버전](https://adot.ai/multillm) 에서 진행 되어야 합니다. 아쉽게도 현재 에이닷 웹버전은 별도 파일 첨부나 이미지 제작 기능 등은 지원하고 있지 않습니다. 현재 지원서나 팀 소개 내용을 보면 해당 기능을 염두에 두고 아이디어를 작성하신 팀들이 많이 있습니다. 이번 1차 기획안 작성시에는 꼭 실제로 가능성이 있는지 에이닷 웹버전에서 테스트하고 검증하여 진행해주시면 좋을 것 같습니다.

- 지원서, 팀 소개, 1차 기획안 등의 내용과 ‘최종 기획안’ 내용은 달려져도 좋습니다. 최대한 많이 시도해보시고 테스트해보세요.

- 기타 참고하면 좋을 만한 내용과 프롬프트 관련 작성 Tip은 이전에 올린 공지사항을 참고해주시면 좋을 것 같습니다.

**Comment by Ricepunchb** [comment]
# CoT 원문
https://arxiv.org/abs/2201.11903
# ToT 원문
https://arxiv.org/abs/2305.10601
# GoT 원문
https://arxiv.org/abs/2308.09687

# 에이닷 로고 svg 파일
![qyW58_TtegmI3CkzMOqKGcsA1zmoDNz6WmjLGhFOWAY97lOo-sbip-m0lmnbZNwUWWASX0W7Nw6Mr9kDT5YR0Pl8jA3QZjKXr6xJlbtRiL_51Ge5TaOXaA1_cE_E6kqg0Qf4MbgS0NtF8GLKkvl_JA](https://github.com/user-attachments/assets/d85921d6-c6d3-4ba1-b543-83113f3d60ee)

**Comment by Ricepunchb** [comment]
[얼리어닷터2기_1차 기획안_v2.pptx](https://github.com/user-attachments/files/18054932/2._1._v2.pptx)

**Finetuning fonts, size, aligns..**
- 폰트는 제목 "나눔스퀘어 Bold", 내용은 "나눔스퀘어라운드 Bold", LLM이름같은 고유명사는 "D2 coding" 폰트로 통일
- 제목부분을 주제목, 부제목 으로 양쪽으로 나누어 얼라인 맞춤
- 내용 슬라이드 중 글머리 기호 부분 줄간격 재설정

**확인 필요사항**
- 11,12번 슬라이드 Method placeholder 변경
- 논문 추가할 포인트
@sjki928

**Comment by sjki928** [comment]
[얼리어닷터2기_1차 기획안_v3](https://github.com/user-attachments/files/18060584/2._1._v3.pptx)

> 11,12번 슬라이드 Method placeholder 변경
논문 추가할 포인트

반영 완료 및 초안을 위한 슬라이드 작성 + 기존 10페이지 검증에 동일 문장 반복 해결

마지막 체크 후 요약문과 함께 업로드
@Ricepunchb

**Comment by Ricepunchb** [comment]
Completed
